#lang ivy1.8

include order
include fba

instance val : unbounded_sequence
instance ballnum : unbounded_sequence

object ballot = {
    type this = struct {
        counter: ballnum,
        value: val
    }
    relation less(B1:this, B2:this)
    relation less_eq(B1:this, B2:this)
    definition less(B1, B2) = counter(B1) < counter(B2)
        | (counter(B1) = counter(B2) & value(B1) < value(B2))
    definition less_eq(B1, B2) = B1 = B2 | less(B1,B2)
    relation less_and_incompatible(B1:this, B2:this)
    definition less_and_incompatible(B1, B2) = less(B1,B2) & value(B1) ~= value(B2)
}

isolate interface = {
    import action externalize(n:node, v:val)
    specification {
        relation externalized(V:val)
        after init {
            externalized(V) := false
        }
        before externalize {
            if intertwined(n) {
                require externalized(V) -> V = v;
                externalized(V) := V = v
            }
        }
        invariant externalized(V1) & externalized(V2) -> V1 = V2
    }
}


object abstract_balloting = {
    # we can use this object as a monitor

    # the following two relations are a relational abstraction of the current ballot of each node
    # if ballnum(n) is the current ballot number of a node, then we should have `started_ballnum(N,ballnum(N))` and `left_ballnum(N,C) = C < ballnum(N)`
    relation started_ballnum(N:node, C:ballnum)
    relation left_ballnum(N:node, C:ballnum)
    # federated voting messages:
    relation voted_prepared(N:node, B:ballot)
    relation accepted_prepared(N:node, B:ballot)
    relation confirmed_prepared(N:node, B:ballot)
    relation voted_committed(N:node, B:ballot)
    relation accepted_committed(N:node, B:ballot)
    relation externalized(N:node, B:ballot)

    isolate actions = {
        after init {
            left_ballnum(N,B) := false;
            started_ballnum(N,B) := false;
            voted_prepared(N,B) := false;
            accepted_prepared(N,B) := false;
            confirmed_prepared(N,B) := false;
            voted_committed(N,B) := false;
            accepted_committed(N,B) := false;
            externalized(N,B) := false;
        }

        action byz_havoc = {
            voted_prepared(N,B) := *;
            require ~(well_behaved(N) & (voted_prepared(N,B) ~= old voted_prepared(N,B)));
            accepted_prepared(N,B) := *;
            require ~(well_behaved(N) & (accepted_prepared(N,B) ~= old accepted_prepared(N,B)));
            voted_committed(N,B) := *;
            require ~(well_behaved(N) & (voted_committed(N,B) ~= old voted_committed(N,B)));
            accepted_committed(N,B) := *;
            require ~(well_behaved(N) & (accepted_committed(N,B) ~= old accepted_committed(N,B)));
            confirmed_prepared(N,B) := *;
            require ~(well_behaved(N) & (confirmed_prepared(N,B) ~= old confirmed_prepared(N,B)));
            externalized(N,B) := *;
            require ~(well_behaved(N) & (externalized(N,B) ~= old externalized(N,B)));
            started_ballnum(N,C) := *;
            require ~(well_behaved(N) & (started_ballnum(N,C) ~= old started_ballnum(N,C)));
            left_ballnum(N,C) := *;
            require ~(well_behaved(N) & (left_ballnum(N,C) ~= old left_ballnum(N,C)));
        }

        action increase_bal_counter(n:node, c:ballnum) = {
            require c > 0 & ~started_ballnum(n,c) & ~left_ballnum(n,c);
            left_ballnum(n, C) := C < c;
            started_ballnum(n, c) := true;
            var b:ballot; # the new ballot
            b.counter := c;
            if exists B . confirmed_prepared(n,B) {
                local bmax:ballot { # max confirmed prepared
                    require confirmed_prepared(n,bmax)
                        & (forall B . confirmed_prepared(n,B) -> ballot.less_eq(B, bmax));
                    b.value := bmax.value;
                }
            }
            voted_prepared(n, b) := true;
        }

        relation quorum_of(N:node, Q:nset)
        definition quorum_of(N,Q) = is_quorum(Q) & member(N,Q)

        action accept_prepared(n:node, b:ballot) = {
            require (exists Q . quorum_of(n,Q) & forall N . member(N,Q) -> voted_prepared(N,b) | accepted_prepared(N,b))
                | exists B . blocks_slices(B,n) & forall N . member(N,B) -> accepted_prepared(N,b);
            # do not contradict previous ballots accepted as committed:
            require ~(accepted_committed(n,B) & ballot.less_and_incompatible(B,b));
            accepted_prepared(n,b) := true;
        }

        action confirm_prepared(n:node, b:ballot) = {
            require exists Q . quorum_of(n,Q) & forall N . member(N,Q) -> accepted_prepared(N,b);
            confirmed_prepared(n,b) := true;
        }

        action vote_to_commit(n:node, b:ballot) = {
            require started_ballnum(n, b.counter) & ~left_ballnum(n, b.counter);
            # in each ballnum we only prepare a single value:
            require ballot.counter(B) = b.counter & voted_prepared(n,B) -> ballot.value(B) = b.value;
            require confirmed_prepared(n,b);
            voted_committed(n,b) := true;
        }

        action accept_committed(n:node, b:ballot) = {
            require exists Q . quorum_of(n,Q) & forall N . member(N,Q) -> voted_committed(N,b) | accepted_committed(N,b)
                | exists B . blocks_slices(B, n) & forall N . member(N,B) -> accepted_committed(N,b);
            require confirmed_prepared(n,b); # important for safety of intertwined but befouled nodes
            require ~(accepted_prepared(n,B) & ballot.less_and_incompatible(b,B));
            accepted_committed(n,b) := true;
        }

        action externalize(n:node, b:ballot) = {
            require exists Q . quorum_of(n,Q) & forall N . member(N,Q) -> accepted_committed(N,b);
            externalized(n,b) := true;
            call interface.externalize(n, b.value);
        }

        export byz_havoc
        export increase_bal_counter
        export accept_prepared
        export confirm_prepared
        export vote_to_commit
        export accept_committed
        export externalize
    } with intertwined_safety_invariants, interface, node_properties, quorum_properties.qi_intertwined, ballot, ballnum, val

    isolate intertwined_safety_invariants = {
        # invariants needed to prove the actions isolate
        # NOTE not much happens in this isolate, as we don't even include ballot:
        # The reasoning that depends on ballot order happens in the actions isolate (which does include ballot)

        # a well-behaved node that confirms something saw a quorum of accepts:
        invariant intertwined(N) & confirmed_prepared(N,B) -> exists Q . is_quorum(Q) & (exists N . intertwined(N) & member(N,Q)) & forall N . member(N,Q) & well_behaved(N) -> accepted_prepared(N,B)
        invariant intertwined(N) & externalized(N,B) -> exists Q . is_quorum(Q)  & (exists N . intertwined(N) & member(N,Q)) & forall N . member(N,Q) & well_behaved(N) -> accepted_committed(N,B)

        # a well-behaved node does not accept something as committed unless it confirmed it prepared
        invariant well_behaved(N) & accepted_committed(N,B) -> confirmed_prepared(N,B)

        # well-behaved nodes do not accept contradictory things:
        invariant well_behaved(N) & accepted_prepared(N,B2) & ballot.less_and_incompatible(B1, B2) -> ~accepted_committed(N,B1)

        invariant intertwined(N) & externalized(N,B) -> interface.externalized(ballot.value(B))
        invariant interface.externalized(V) -> exists N,B . intertwined(N) & externalized(N,B) & ballot.value(B) = V # quantifier alternation here...
    } with abstract_balloting.actions, node_properties, interface

    isolate extra_invariants = {
        # we start at a ballnum > 0:
        invariant well_behaved(N) & started_ballnum(N,C) -> C > 0
        # if a node has started ballnum C then it left all lower ballnums:
        invariant well_behaved(N) & started_ballnum(N,C2) & C1 < C2 -> left_ballnum(N,C1)
        invariant well_behaved(N) & left_ballnum(N,C2) & C1 < C2 -> left_ballnum(N,C1)

        # only vote in started ballnums:
        invariant well_behaved(N) & (voted_prepared(N,B) | voted_committed(N,B)) -> started_ballnum(N, ballot.counter(B))


        invariant well_behaved(N) & voted_prepared(N,B) -> started_ballnum(N, ballot.counter(B))
        invariant well_behaved(N) & voted_prepared(N,B1) & voted_prepared(N,B2) & ballot.counter(B1) = ballot.counter(B2) -> B1 = B2

    } with abstract_balloting.actions, ballnum

    isolate intact_invariants = {

        invariant intact(N) & voted_prepared(N,B1) & voted_prepared(N,B2) & ballot.counter(B1) = ballot.counter(B2) -> ballot.value(B1) = ballot.value(B2)
        invariant intact(N) & accepted_prepared(N,B1) & accepted_prepared(N,B2) & ballot.counter(B1) = ballot.counter(B2) -> ballot.value(B1) = ballot.value(B2)

        # accept/confirm if quorum voted/accepted:
        invariant intact(N) & confirmed_prepared(N,B) -> exists Q . is_quorum(Q) & member(N,Q) & forall N . member(N,Q) & intact(N) -> accepted_prepared(N,B)
        invariant intact(N) & accepted_prepared(N,B) -> exists Q . is_quorum(Q) & (exists N . intact(N) & member(N,Q)) & forall N . member(N,Q) & intact(N) -> voted_prepared(N,B)
        invariant intact(N) & externalized(N,B) -> exists Q . is_quorum(Q) & member(N,Q) & forall N . member(N,Q) & intact(N) -> accepted_committed(N,B)
        invariant intact(N) & accepted_committed(N,B) -> exists Q . is_quorum(Q) & (exists N . intact(N) & member(N,Q)) & forall N . member(N,Q) & intact(N) -> voted_committed(N,B)

        invariant well_behaved(N) & voted_committed(N,B) -> confirmed_prepared(N,B)
        # important invariant: a node does not prepare a value that contradicts a previous vote to commit unless that vote cannot reach quorum threshold
        invariant is_quorum(Q) & (exists N . intact(N) & member(N,Q)) & intact(N1) & ballot.less_and_incompatible(B1,B2) & voted_committed(N1,B1) & voted_prepared(N1,B2) -> (exists N . intact(N) & member(N,Q) & left_ballnum(N,ballot.counter(B1)) & ~voted_committed(N,B1))

        # An accepted prepared value cannot be contradicted.
        invariant intact(N2) & accepted_prepared(N2,B2) & intact(N1) & ballot.less_eq(B1, B2) & accepted_committed(N1,B1) -> ballot.value(B1) = ballot.value(B2)
    } with abstract_balloting.actions, node_properties, quorum_properties, ballnum, val, ballot, intertwined_safety_invariants, extra_invariants
}
