#lang ivy1.7
# check with ivy_check isolate=abstract_protocol seed=$RANDOM complete=fo constant_space_unauth.ivy

# We start with the domain model (nodes, rounds, values, quorums, blocking sets, etc.)
include order

instance node : iterable # nodes are a set with an order, that can be iterated over (see order.ivy in the standard library)

type value

instance round : unbounded_sequence # this establishes that rounds are totally ordered by < with least element 0
type quorum
type blocking # blocking sets

relation well_behaved(N:node) # NOTE: Use only in the proof! Nodes do not know that.

relation q_member(N:node, Q:quorum) # membership relation
relation b_member(N:node, B:blocking) # membership relation

trusted isolate intersection_assumptions = {
    property [quorum_intersection] exists N. well_behaved(N) & q_member(N, Q1) & q_member(N, Q2) # every two quorums have a well-behaved node in common
    property [blocking_assm] exists N . well_behaved(N) & b_member(N,B) # every blocking set contains a well-behaved node
}

isolate abstract_protocol = {

    relation left_round(N:node, R:round)
    relation proposal(R:round, V:value)
    relation key_1(N:node, R:round, V:value)
    relation key_2(N:node, R:round, V:value)
    relation key_3(N:node, R:round, V:value)
    relation vote(N:node, R:round, V:value)
    relation decided(N:node, R:round, V:value)

    after init {
        proposal(R,V) := false;
        key_1(N,R,V) := false;
        key_2(N,R,V) := false;
        key_3(N,R,V) := false;
        vote(N,R,V) := false;
        decided(N,R,V) := false;
        left_round(N,R) := false;
    }

    export action join_round(n:node, r:round) = {
        require ~left_round(n,r);
        left_round(n,R) := R < r;
    }

    relation temp(N:node, R:round, V:value) # we'll use this as a temporary variable
    relation temp_2(N:node, R:round, V:value) # we'll use this as a temporary variable

    relation claims_safe_at(N:node, R:round, V:value)
    definition claims_safe_at(N:node, r:round, v:value) =
        exists R1 . R1 >= r & ( # temp is e.g. a copy of key_1
                temp(N,R1,v)
            |   exists R2,V1,V2 . R1 < R2 & temp(N,R1,V1) & temp(N,R2,V2) & V1 ~= V1 # everything is safe at R1
        )
    # NOTE: we only need two things to compute claims_safe_at: the highest temp round and value, and the second highest temp round

    relation shows_safe_at(R1:round, R2:round, V:value, Q:quorum, B:blocking)
    definition shows_safe_at(r1:round, r2:round, v:value, q:quorum, b:blocking) =
        # q and b show that v is safe at r2, meaning nothing but v is choosable at a round r such that r < r2
        # r1 is the max round r1 < r2 in which q voted, if any
        (forall N,R . q_member(N,q) & R < r2 -> left_round(N,r2))
    &
        (
            (       r1 < r2
                &   (forall N . b_member(N,b) -> claims_safe_at(N,r1,v)) # v is safe at r1
                &   (forall N,V . q_member(N,q) & temp_2(N,r1,V) -> V = v) # only v voted for at r1, if any, among q
                &   (forall N,R,V . q_member(N,q) & r1 < R & R < r2 -> ~temp_2(N,R,V)) ) # no vote among q after r1
        |
            (   forall N,R,V . q_member(N,q) & R < r2 -> ~temp_2(N,R,V) ) ) # nobody ever voted before r2

    export action do_key_1(n:node, r:round, v:value) = {
        require ~key_1(n,r,V) & ~left_round(n,r);
        # non-leaders use key_1 and vote to determine what is safe:
        temp(N,R,V) := key_1(N,R,V);
        temp_2(N,R,V) := vote(N,R,V);
        require exists R,Q,B . shows_safe_at(R, r, v, Q, B);
        key_1(n, r, v) := true;
        left_round(n, R) := R < r;
    }

    export action do_key_2(n:node, r:round, v:value) = {
        require ~key_2(n,r,V) & ~left_round(n,r);
        require exists Q . q_member(N,Q) -> key_1(N,r,v);
        key_2(n, r, v) := true;
        left_round(n, R) := R < r;
    }

    export action do_key_3(n:node, r:round, v:value) = {
        require ~key_3(n,r,V) & ~left_round(n,r);
        require exists Q . q_member(N,Q) -> key_2(N,r,v);
        key_3(n, r, v) := true;
        left_round(n, R) := R < r;
    }

    export action do_vote(n:node, r:round, v:value) = {
        require ~vote(n,r,V) & ~left_round(n,r);
        require exists Q . q_member(N,Q) -> key_3(N,r,v);
        vote(n, r, v) := true;
        left_round(n, R) := R < r;
    }

    export action decide(n:node, r:round, v:value, q:quorum) = {
        require q_member(N, q) -> vote(N, r, v);
        decided(n, r, v) := true;
    }

    export action propose(r:round, v:value, q:quorum, r1:round) = {
        # leaders use key_2 and key_3 to determine what is safe:
        temp(N,R,V) := key_2(N,R,V);
        temp_2(N,R,V) := key_3(N,R,V);
        require exists R,Q,B . shows_safe_at(R, r, v, Q, B);
        proposal(r,v) := true;
        assert safe_at(r,v);
    }

    # notion of choosable and safe at:
    ##################################
    relation choosable(R:round, V:value)
    definition [choosable_def] choosable(R,V) = exists Q . forall N . well_behaved(N) & q_member(N,Q) -> ~left_round(N,R) | vote(N,R,V)
    relation safe_at(R:round, V:value)
    definition [safe_at_def] safe_at(R2,V2) = forall R1,V1 . R1 < R2 & V1 ~= V2 -> ~choosable(R1,V1)

    # the agreement property:
    # #####################
    invariant [safety] well_behaved(N1) & well_behaved(N2) & decided(N1,R1,V1) & decided(N2,R2,V2) -> V1 = V2

    invariant well_behaved(N) & key_1(N,R,V) -> safe_at(R,V)
    invariant well_behaved(N) & key_2(N,R,V) -> safe_at(R,V)
    invariant well_behaved(N) & key_3(N,R,V) -> safe_at(R,V)
    invariant well_behaved(N) & vote(N,R,V) -> safe_at(R,V)
invariant (exists N1 . well_behaved(N1) & decided(N1,R,V)) -> exists Q. forall N2. well_behaved(N2) & q_member(N2, Q) -> vote(N2,R,V)
    invariant (exists N1 . well_behaved(N1) & vote(N1,R,V)) -> exists Q. forall N2. well_behaved(N2) & q_member(N2, Q) -> key_3(N2,R,V)
    invariant (exists N1 . well_behaved(N1) & key_3(N1,R,V)) -> exists Q. forall N2. well_behaved(N2) & q_member(N2, Q) -> key_2(N2,R,V)
    invariant (exists N1 . well_behaved(N1) & key_2(N1,R,V)) -> exists Q. forall N2. well_behaved(N2) & q_member(N2, Q) -> key_1(N2,R,V)

    # now, supporting invariants:
    #############################

    # if a node left round R2>R1, then it also left R1
    invariant well_behaved(N) & left_round(N,R2) & R1 < R2 -> left_round(N,R1)

    # nodes stop preparing or committing in lower rounds when doing so in a higher round:
    invariant well_behaved(N) & key_1(N,R2,V2) & R1 < R2 -> left_round(N,R1)
    invariant well_behaved(N) & key_2(N,R2,V2) & R1 < R2 -> left_round(N,R1)
    invariant well_behaved(N) & key_3(N,R2,V2) & R1 < R2 -> left_round(N,R1)
    invariant well_behaved(N) & vote(N,R2,V2) & R1 < R2 -> left_round(N,R1)

    invariant well_behaved(N) & key_1(N,R,V) & key_1(N,R,V2) -> V = V2
    invariant well_behaved(N) & key_2(N,R,V) & key_2(N,R,V2) -> V = V2
    invariant well_behaved(N) & key_3(N,R,V) & key_3(N,R,V2) -> V = V2
    invariant well_behaved(N) & vote(N,R,V) & vote(N,R,V2) -> V = V2


} with round, intersection_assumptions

# Concrete protocol model

object pair_opt_t = {
    type this
    individual rnd : round
    individual val : value
    individual present: bool
}

object round_opt_t = {
    type this
    individual rnd : round
    individual present: bool
}

type msg

object proposal_msg = {
    variant this of msg = struct {
        src : node,
        rnd : round,
        val : value
    }
}

object suggest_msg = {
    variant this of msg = struct {
        src : node,
        key_2 : pair_opt_t,
        prev_key2 : round_opt_t,
        key3 : pair_opt_t,
        val : value
    }
}

object proof_msg = {
    variant this of msg = struct {
        src : node,
        vote : pair_opt_t,
        key1 : pair_opt_t
    }
}

object key_1_msg = {
    variant this of msg = struct {
        src : node,
        rnd : round,
        val : value
    }
}

object key_2_msg = {
    variant this of msg = struct {
        src : node,
        rnd : round,
        val : value
    }
}

object key_3_msg = {
    variant this of msg = struct {
        src : node,
        rnd : round,
        val : value
    }
}

object vote_msg = {
    variant this of msg = struct {
        src : node,
        rnd : round,
        val : value
    }
}

type phase_t = {suggest_phase, key_1_phase, key_2_phase, key_3_phase, vote_phase}

isolate protocol = {

    object server(n:node) = {

        # NOTE: there seem to be a bug in Ivy which prevents us from using struct types here so we flatten them out

        individual rnd: round # the current round of the node
        individual phase: phase_t

        individual vote: pair_opt_t
        individual key_3: pair_opt_t
        individual key_2: pair_opt_t
        individual prev_key_2: round_opt_t
        individual key_1: pair_opt_t
        individual prev_key_1: round_opt_t

        individual decided: bool
        individual decision:value

        # state used to progress through phases:
        relation key_3s(N:node,V:value) # key_3 msgs received in the current round
        relation key_2s(N:node,V:value) # key_2 msgs received in the current round
        relation key_1s(N:node,V:value) # key_1 msgs received in the current round
        relation votes(N:node,V:value) # vote msgs received in the current round

        # state used by a leader to pick a proposal:
        relation joined(N:node) # who joined the current round
        relation highest_vote(N:node, R:round, V:value) # highest votes
        relation highest_key_2(N:node, R:round, V:value)
        relation highest_prev_key_2(N:node, R:round)

        # state used by a non-leader leader to determine what values are safe the current round:
        relation highest_key_1(N:node, R:round, V:value)
        relation highest_prev_key_1(N:node, R:round)


        after init {
            # call reset_round_state; TODO: BUG: seems we can't call anything in init
            rnd := 0;
            vote.present := false;
            key_3.present := false;
            key_2.present := false;
            key_1.present := false;
            decided := false;
            phase := suggest_phase;
            key_3s(N,V) := false;
            key_2s(N,V) := false;
            key_1s(N,V) := false;
            votes(N,V) := false;
            joined(N) := false;
            highest_vote(N,R,V) := false;
            highest_key_2(N,R,V) := false;
            highest_prev_key_2(N,R) := false;
            highest_key_1(N,R,V) := false;
            highest_prev_key_1(N,R) := false;
        }

        action reset_round_state = {
            phase := suggest_phase;
            key_3s(N,V) := false;
            key_2s(N,V) := false;
            key_1s(N,V) := false;
            votes(N,V) := false;
            joined(N) := false;
            highest_vote(N,R,V) := false;
            highest_key_2(N,R,V) := false;
            highest_prev_key_2(N,R) := false;
            highest_key_1(N,R,V) := false;
            highest_prev_key_1(N,R) := false;
        }

        # a leader starts a new round:
        export action start_round(r:round) = {
            require r > rnd;
            rnd := r;

            call reset_round_state;

            if proposers.is_proposer(n,r) {
                joined(N) := N = n;
            }
            else {
                # var m:start_round_msg;
                # m.src := n;
                # m.rnd := r;
                # m.voted := voted;
                # m.last_vote_rnd := last_vote_rnd;
                # m.last_vote_val := last_vote_val;
            }
        }

        # implement shim.start_round_handler.handle(m:start_round_msg) {
            # if (m.rnd = rnd) {
                # joined(m.src) := true;
                # highest_vote(N,R,V) := highest_vote(N,R,V) | (m.voted & N = m.src & R = m.last_vote_rnd & V = m.last_vote_val);
            # }
        # }

        # export action propose(v:value, q:quorum, r1:round) = {
            # require q_member(N,q) -> joined(N); # all members of q have joined round r
            # require r1 < rnd;
            # require
                # (forall N,R,V . q_member(N,q) -> ~highest_vote(N,R,V)) # no member of q ever voted
            # |   (forall N,R,V.
                    # (q_member(N,q) & highest_vote(N,R,V) -> R <= r1) # r1 is the max voted round in q
                # &   (q_member(N,q) & highest_vote(N,r1,V) -> V = v) # only v was voted in round r1 among q
                # &   safe_at(r1,v) ); # v is safe at r1
            # # broadcast a propose msg:
            # var m: proposal_msg;
            # m.src := n;
            # m.rnd := rnd;
            # m.val := v;
            # call shim.broadcast(n,m);
        # }

        # implement shim.proposal_handler.handle(m:proposal_msg) {
            # if (m.rnd = rnd & (forall V. ~prepared(n,V)) & (locked -> last_vote_val = m.val)) {
                # prepared(n,m.val) := true;
                # var m2:prepare_msg;
                # m2.src := n;
                # m2.rnd := rnd;
                # m2.val := m.val;
                # call shim.broadcast(n,m);
            # }
        # }

        # implement shim.prepare_handler.handle(m:prepare_msg) {
            # if (m.rnd = rnd) {
                # prepared(m.src, m.val) := true;
            # }
        # }

        # relation safe_at_(R:round, V:value) # we use this relation as a temporary relation variable
        # action new_safe_val(r:round, v:value) = {
            # # here we update max_safe and max_all_safe knowing that v is safe at r
            # safe_at_(R,V) := *; # non-deterministic choice
            # # now we make sure that safe_at_ describes what's safe according to what the node knows:
            # assume safe_at_(R,V) = safe_at(R,V) | (R <= r & V = v);
            # # then we set max_safe and max_all_safe accordingly
            # max_safe_val := *; # this is non-deterministic choice
            # max_safe_rnd := *;
            # assume safe_at_(R,V) -> R <= max_safe_rnd; # max_safe_rnd is the max round at which we know a value is safe
            # assume safe_at_(max_safe_rnd,max_safe_val); # and max_safe_val is a corresponding value
            # max_all_safe := *;
            # assume R <= max_all_safe -> safe_at_(R,V);
            # # now send msgs:
            # # send all_safe msg:
            # var m:all_safe_msg;
            # m.src := n;
            # m.rnd := max_all_safe;
            # call shim.broadcast(n,m);
            # # send safe_at msg:
            # var m2:safe_at_msg;
            # m2.src := n;
            # m2.rnd := max_safe_rnd;
            # m2.val := max_safe_val;
            # call shim.broadcast(n,m2);
        # }


        # implement shim.safe_at_handler.handle(m:safe_at_msg) {
            # heard_safe_at(m.src, R, V) := R = m.rnd & V = m.val;
        # }

        # implement shim.all_safe_handler.handle(m:all_safe_msg) {
            # heard_all_safe(m.src, R) := R = m.rnd;
        # }

        # export action update_max_all_safe(b:blocking, r:round) = {
            # require max_all_safe < r;
            # require b_member(N,b) -> exists R . r <= R & heard_all_safe(N, R);
            # max_all_safe := r;
            # if (max_safe_rnd < max_all_safe) {
                # max_safe_rnd := max_all_safe
            # }
        # }

        # export action update_max_safe(b:blocking, r:round, v:value) = {
            # require max_safe_rnd <= r;
            # require b_member(N,b) -> exists R . r <= R & heard_safe_at(N, R, v);
            # call new_safe_val(r, v);
        # }

        # export action vote(v:value, q:quorum) = {
            # require q_member(N,q) -> prepared(N,v);
            # locked := true;
            # # update last_vote:
            # voted := true;
            # last_vote_val := v;
            # last_vote_rnd := rnd;
            # call new_safe_val(rnd, v);
            # # send vote msg:
            # var m:vote_msg;
            # m.rnd := rnd;
            # m.val := v;
            # call shim.broadcast(n,m);
        # }

        # implement shim.vote_handler.handle(m:vote_msg) {
            # if (m.rnd = rnd) {
                # votes(m.src, m.val) := true;
            # }
        # }

        # export action decide(v:value, q:quorum) = {
            # require q_member(N,q) -> votes(N,v);
            # decision := v;
        # }
    }
} with round, intersection_assumptions, shim

isolate proposers = {
    # Each round has a unique proposer. In order to avoid a
    # function from round to node (which makes verification more difficult), we
    # abstract over this function using a relation.
    relation is_proposer(N:node, R:round)
    export action get_proposer(r:round) returns (n:node)
    specification {
        property is_proposer(N1,R) & is_proposer(N2,R) -> N1 = N2
        after get_proposer {
            ensure is_proposer(n,r);
        }
    }
    # this can be implemented by taking the round modulo the number of nodes:
    implementation {
        function f(R:round):node
        definition f(r:round) = <<<r % `node.size`>>>
        definition is_proposer(N,R) = N = f(R)
        implement get_proposer {
            n := f(r);
        }
    }
}

trusted isolate shim = {

    # In order not repeat the same code for each handler, we use a handler
    # module parameterized by the type of msg it will handle.
    module handler(t) = {
        action handle(dst:node,m:t)
        object spec = {
            before handle {
                assert exists M:msg . M *> m & sent(M,dst)
            }
        }
    }

    instance proposal_handler : handler(proposal_msg)
    instance suggest_handler : handler(suggest_msg)
    instance proof_handler : handler(proof_msg)
    instance key_1_handler : handler(key_1_msg)
    instance key_2_handler : handler(key_2_msg)
    instance key_3_handler : handler(key_3_msg)
    instance vote_handler : handler(vote_msg)

    relation sent(M:msg,N:node)

    action broadcast(src:node,m:msg)
    action send(src:node,dst:node,m:msg)

    specification {
        after init {
            sent(M,D) := false;
        }
        before broadcast {
            sent(m,D) := true
        }
        before send {
            sent(m,dst) := true
        }
    }
}
